model: resnet18
dataset: imagenettewoof
# dataset: synthetic
attribution_methods:
  - GradCAMPlusPlus
  - LayerCAM
  - ScoreCAM
metrics:
  - road_combined
  - deletioncurveauc
  - insertioncurveauc
  - infidelity
  - averagedrop
  - coherency
  - complexity
  # - roc_auc
  # - mass_iou
upscale_methods:
  - SimpleUpsampling
  # - ERFUpsamplingFast

model_path: ./ResNet18_Imagenettewoof.pth
output_path: ./results_resnet18_imagenettewoof.csv
device: cuda:1
